"""Проверка миграции

Revision ID: 19f781546557
Revises: 61e900a85e80
Create Date: 2023-05-14 19:37:19.656384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19f781546557'
down_revision = '61e900a85e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sug_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('menu_items')
    op.drop_table('menu_subitems')
    op.drop_constraint('menu_ibfk_1', 'menu', type_='foreignkey')
    op.drop_column('menu', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('menu_ibfk_1', 'menu', 'menu', ['father_id'], ['id'])
    op.create_table('menu_subitems',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('item', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('menu_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('link', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('is_list', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('sug_post')
    # ### end Alembic commands ###
