"""Dynamic page archive fields

Revision ID: 21d3a64dad9a
Revises: 42a9f0496347
Create Date: 2017-02-26 11:09:49.850788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d3a64dad9a'
down_revision = '42a9f0496347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('uploaded', sa.DateTime(), nullable=True))
    op.add_column('page', sa.Column('archive_of_page', sa.Integer(), nullable=True))
    op.add_column('page', sa.Column('archived', sa.DateTime(), nullable=True))
    op.add_column('page', sa.Column('is_archive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'is_archive')
    op.drop_column('page', 'archived')
    op.drop_column('page', 'archive_of_page')
    op.drop_column('file', 'uploaded')
    # ### end Alembic commands ###
