"""empty message

Revision ID: cb9ef1ebff7f
Revises: 19f781546557
Create Date: 2023-05-14 19:49:28.339649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9ef1ebff7f'
down_revision = '19f781546557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'number')
    # ### end Alembic commands ###
